In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [16]:
test = pd.read_csv('Sample.csv')
test.sample(5)

artist                        album  \
31             The Paper Kites         twelvefour: outtakes   
33                 Iron & Wine             Call It Dreaming   
37       Red Hot Chili Peppers  By the Way (Deluxe Edition)   
2                   CASTLEBEAT                   CASTLEBEAT   
3   You'll Never Get to Heaven                       Images   

           track_name                track_id  popularity  \
31              Holes  4fpAxDV1fhSHMotzyKkFhz          40   
33   Call It Dreaming  0iWUW8UNkmyUa8Aa6anow6          27   
37         Can't Stop  3ZOEytgrvLwQaqXreDs2Jx          82   
2    Change Your Mind  4omurqpm7aWH9VVz2Ii4yO          54   
3   Beyond the Clouds  6vMaCzTnismT6N45MDCMfa          41   

                                               genres  danceability  energy  \
31  ['australian indie folk', 'indie folk', 'stomp...         0.526   0.318   
33  ['acoustic pop', 'indie folk', 'indie pop', 'n...         0.509   0.515   
37  ['alternative rock', 'funk metal', 'funk rock'...         0.618   0.938   
2   ['bedroom pop', 'indie garage rock', 'indie po...         0.384   0.578   
3       ['ambient pop', 'london on indie', 'nu gaze']         0.633   0.575   

    key  loudness  mode  speechiness  instrumentalness  liveness  valence  \
31    1   -13.514     1       0.0280          0.347000    0.1030   0.1620   
33    5    -9.442     1       0.0316          0.000058    0.0966   0.7170   
37    9    -3.442     1       0.0456          0.000000    0.1670   0.8750   
2    11    -9.624     1       0.0312          0.886000    0.1250   0.0984   
3     7    -9.667     0       0.0298          0.924000    0.1050   0.2390   

      tempo  duration_ms  time_signature  reverb  
31   79.981       268933               3       0  
33   80.089       231760               4       0  
37   91.455       269000               4       0  
2   150.013       297273               4       1  
3   117.520       248681               4       1

In [17]:
test = test.drop('genres', axis=1)

In [18]:
X = test.iloc[:, 4:-3].values
y = test.iloc[:, -1].values

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [22]:
predictions = knn.predict(X_test)
print(np.concatenate((predictions.reshape(len(predictions),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, predictions))
accuracy_score(y_test, predictions)

[[9 1]
 [0 3]]


0.9230769230769231

In [24]:
test.columns

Index(['artist', 'album', 'track_name', 'track_id', 'popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms',
       'time_signature', 'reverb'],
      dtype='object')

In [28]:
test = pd.read_csv('test.csv')
test = test[['popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'instrumentalness', 'liveness', 'valence', 'tempo']]
test

popularity  danceability  energy  key  loudness  mode  speechiness  \
0           0         0.508   0.785    0    -7.286     0       0.0295   

   instrumentalness  liveness  valence    tempo  
0             0.125     0.142     0.61  147.073

In [29]:
test_X = test.values
test_X

array([[ 0.00000e+00,  5.08000e-01,  7.85000e-01,  0.00000e+00,
        -7.28600e+00,  0.00000e+00,  2.95000e-02,  1.25000e-01,
         1.42000e-01,  6.10000e-01,  1.47073e+02]])

In [30]:
print(knn.predict(sc.transform(test_X)))

[1]
