In [120]:
pd.reset_option('display.max_rows')

In [121]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [122]:
test = pd.read_csv('Sample.csv')
test.sample(5)

artist                             album  \
33      Iron & Wine                  Call It Dreaming   
13   Tyler Burkhart                       Sweet spell   
38        The Kooks                 Junk Of The Heart   
27   The Chieftains                     Voice of Ages   
29  The Band CAMINO  I Spend Too Much Time in My Room   

                          track_name                track_id  popularity  \
33                  Call It Dreaming  0iWUW8UNkmyUa8Aa6anow6          27   
13       In the bathtub of the world  5oE2tnxS2GUe1oxDbVjvls          35   
38         Junk Of The Heart (Happy)  5p50gxcAYYeWPrBVEPHgUt          28   
27         Down In The Willow Garden  1lryIQgUxmnNNh37oLCN6G          41   
29  I Spend Too Much Time in My Room  6XHikJpK06NoXaFwkH4tPL          50   

                                               genres  danceability  energy  \
33  ['acoustic pop', 'indie folk', 'indie pop', 'n...         0.509   0.515   
13                             ['lancaster pa indie']         0.560   0.443   
38          ['brighton indie', 'modern rock', 'rock']         0.604   0.894   
27                           ['celtic', 'irish folk']         0.264   0.155   
29  ['electropop', 'hopebeat', 'indie cafe pop', '...         0.480   0.439   

    key  loudness  mode  speechiness  instrumentalness  liveness  valence  \
33    5    -9.442     1       0.0316          0.000058    0.0966    0.717   
13    0    -8.395     0       0.0277          0.844000    0.0964    0.150   
38    2    -5.000     1       0.0370          0.000000    0.0299    0.901   
27    9   -15.250     1       0.0329          0.130000    0.1070    0.181   
29    9    -7.221     1       0.0250          0.003850    0.5140    0.152   

      tempo  duration_ms  time_signature  reverb  
33   80.089       231760               4       0  
13  119.869       442848               3       1  
38  145.017       187253               4       0  
27   98.414       256067               3       0  
29   97.055       272378               4       0

In [123]:
test = test.drop('genres', axis=1)

In [124]:
X = test.iloc[:, 4:-3].values
y = test.iloc[:, -1].values

In [125]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [126]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [127]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [128]:
predictions = knn.predict(X_test)
print(np.concatenate((predictions.reshape(len(predictions),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [129]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, predictions))
accuracy_score(y_test, predictions)

[[9 1]
 [0 3]]


0.9230769230769231

In [130]:
test.columns

Index(['artist', 'album', 'track_name', 'track_id', 'popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms',
       'time_signature', 'reverb'],
      dtype='object')

In [182]:
test = pd.read_csv('test.csv')
test = test[['popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'instrumentalness', 'liveness', 'valence', 'tempo']]
test

popularity  danceability  energy  key  loudness  mode  speechiness  \
0          73         0.369   0.467    5    -9.018     1       0.0274   

   instrumentalness  liveness  valence   tempo  
0              0.46     0.109    0.174  94.473

In [183]:
test_X = test.values
test_X

array([[ 7.3000e+01,  3.6900e-01,  4.6700e-01,  5.0000e+00, -9.0180e+00,
         1.0000e+00,  2.7400e-02,  4.6000e-01,  1.0900e-01,  1.7400e-01,
         9.4473e+01]])

In [184]:
print(knn.predict(sc.transform(test_X)))

[0]
